### ISSUE TITLE
Underrot error

### ISSUE THREAD

**Issue by kittykiller** [DeadlyBossMods/DBM-Dungeons#122]
getting this error in underrot from faceless corruptor when they start casting maddening gaze.

11x DBM-Core/DBM-Core.lua:10158: attempt to compare number with boolean
[string "@DBM-Core/DBM-Core.lua"]:10158: in function `Start'
[string "@DBM-Party-BfA/TheUnderrot/UnderrotTrash.lua"]:85: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1035: in function <DBM-Core/DBM-Core.lua:1022>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1035: in function <DBM-Core/DBM-Core.lua:1022>

Locals:
self = <table> {
 spellId = 272609
 keep = "|TInterface\EncounterJournal\UI-EJ-Icons.blp:20:20:0:0:255:66:70:86:7:27|t"
 icon = 136214
 type = "cd"
 id = "Timer272609cd"
 option = "Timer272609cd"
 countdownMax = 3
 countdown = true
 colorType = 3
 name = "Maddening Gaze"
 mod = <table> {
 }
 timer = 15.700000
 startedTimers = <table> {
 }
}
timer = 15.700000
id = "Timer272609cd	Creature-0-3781-1841-692-138281-00010F27B1"
colorId = 3
countVoice = true
countVoiceMax = 3
(*temporary) = "boolean"
(*temporary) = true
(*temporary) = "boolean"
(*temporary) = "	Creature-0-3781-1841-692-138281-00010F27B1"
(*temporary) = true
(*temporary) = "	Creature-0-3781-1841-692-138281-00010F27B1"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with boolean"
DBM = <table> {
 SelectGossip = <function> defined @DBM-Core/DBM-Core.lua:2787
 GetUnitIdFromCID = <function> defined @DBM-Core/DBM-Core.lua:2712
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core/DBM-Core.lua:4574
 StopLogging = <function> defined @DBM-Core/DBM-Core.lua:5839
 FindScenarioIDs = <function> defined @DBM-Core/DBM-Core.lua:6838
 GetNumGuildPlayersInZone = <function> defined @DBM-Core/DBM-Core.lua:2453
 VibrateController = <function> defined @DBM-Core/DBM-Core.lua:6804
 FindDungeonMapIDs = <function> defined @DBM-Core/DBM-Core.lua:6830
 GetUnitIdFromGUID = <function> defined @DBM-Core/DBM-Core.lua:2534
 CopyProfile = <function> defined @DBM-Core/DBM-Core.lua:1940
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core/DBM-Core.lua:4931
 CHAT_MSG_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:6565
 SendPVPTimers = <function> defined @DBM-Core/DBM-Core.lua:6363
 DeleteProfile = <function> defined @DBM-Core/DBM-Core.lua:1957
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core/modules/UpdateReminder.lua:76
 GetRaidRoster = <function> defined @DBM-Core/DBM-Core.lua:2489
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core/DBM-Core.lua:4696
 FireEvent = <function> defined @DBM-Core/DBM-Core.lua:1848
 CreateModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:89
 SCENARIO_COMPLETED = <function> defined @DBM-Core/DBM-Core.lua:3450
 IsEnabled = <function> defined @DBM-Core/DBM-Core.lua:6651
 GetMyPlayerInfo = <function> defined @DBM-Core/DBM-Core.lua:2557
 ADDON_LOADED = <function> defined @DBM-Core/DBM-Core.lua:1530
 IconNumToTexture = <function> defined @DBM-Core/DBM-Core.lua:6819
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core/DBM-Core.lua:2424
 AddDefeatSound = <function> defined @DBM-Core/modules/Sounds.lua:117
 SortByMeleeRoster = <function> defined @DBM-Core/DBM-Core.lua:7678
 HudMap = <table> {
 }
 GetBossUnitId = <function> defined @DBM-Core/DBM-Core.lua:2694
 lastAntiSpamFLASH = 11870.396000
 AddDefaultOptions = <function> defined @DBM-Core/DBM-Core.lua:2810
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core/DBM-Core.lua:3780
 InfoFrame = <table> {
 }
 SendCombatInfo = <function> defined @DBM-Core/DBM-Core.lua:6385
 FilterRaidBossEmote = <function> defined @DBM-Core/DBM-Core.lua:1365
 RequestTimers = <function> defined @DBM-Core/DBM-Core.lua:6260
 CINEMATIC_START = <function> defined @DBM-Core/DBM-Core.lua:6873
 VoiceVersions = <table> {
 }
 Voices = <table> {
 }
 AddOns = <table> {
 }
 Options = <table>

**Comment by QartemisT** [comment]
This is now fixed in the latest DBM-Dungeons alpha :)

**Comment by kittykiller** [comment]
still getting an error with latest version.

8x DBM-Core/DBM-Core.lua:10177: attempt to compare number with boolean
[string "@DBM-Core/DBM-Core.lua"]:10177: in function `Start'
[string "@DBM-Party-BfA/TheUnderrot/UnderrotTrash.lua"]:85: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1037: in function <DBM-Core/DBM-Core.lua:1024>
[string "=(tail call)"]: ?
[string "@DBM-Core/DBM-Core.lua"]:1037: in function <DBM-Core/DBM-Core.lua:1024>

Locals:
self = <table> {
 spellId = 272609
 keep = true
 icon = 136214
 type = "cd"
 id = "Timer272609cd"
 option = "Timer272609cd"
 countdown = 3
 colorType = 3
 name = "Maddening Gaze"
 mod = <table> {
 }
 timer = 15.700000
 startedTimers = <table> {
 }
 inlineIcon = "|TInterface\EncounterJournal\UI-EJ-Icons.blp:20:20:0:0:255:66:70:86:7:27|t"
}
timer = 15.700000
isCountTimer = false
id = "Timer272609cd	Creature-0-3781-1841-16118-138281-000016D210"
colorId = 3
countVoice = true
countVoiceMax = 4
(*temporary) = "boolean"
(*temporary) = true
(*temporary) = "boolean"
(*temporary) = "	Creature-0-3781-1841-16118-138281-000016D210"
(*temporary) = true
(*temporary) = "	Creature-0-3781-1841-16118-138281-000016D210"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with boolean"
DBM = <table> {
 SelectGossip = <function> defined @DBM-Core/DBM-Core.lua:2789
 GetUnitIdFromCID = <function> defined @DBM-Core/DBM-Core.lua:2714
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core/DBM-Core.lua:4576
 StopLogging = <function> defined @DBM-Core/DBM-Core.lua:5841
 FindScenarioIDs = <function> defined @DBM-Core/DBM-Core.lua:6840
 GetNumGuildPlayersInZone = <function> defined @DBM-Core/DBM-Core.lua:2455
 VibrateController = <function> defined @DBM-Core/DBM-Core.lua:6806
 FindDungeonMapIDs = <function> defined @DBM-Core/DBM-Core.lua:6832
 GetUnitIdFromGUID = <function> defined @DBM-Core/DBM-Core.lua:2536
 CopyProfile = <function> defined @DBM-Core/DBM-Core.lua:1942
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core/DBM-Core.lua:4933
 CHAT_MSG_WHISPER = <function> defined @DBM-Core/DBM-Core.lua:6567
 SendPVPTimers = <function> defined @DBM-Core/DBM-Core.lua:6365
 DeleteProfile = <function> defined @DBM-Core/DBM-Core.lua:1959
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core/modules/UpdateReminder.lua:76
 GetRaidRoster = <function> defined @DBM-Core/DBM-Core.lua:2491
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core/DBM-Core.lua:4698
 FireEvent = <function> defined @DBM-Core/DBM-Core.lua:1850
 CreateModLocalization = <function> defined @DBM-Core/modules/objects/Localization.lua:89
 SCENARIO_COMPLETED = <function> defined @DBM-Core/DBM-Core.lua:3452
 IsEnabled = <function> defined @DBM-Core/DBM-Core.lua:6653
 GetMyPlayerInfo = <function> defined @DBM-Core/DBM-Core.lua:2559
 ADDON_LOADED = <function> defined @DBM-Core/DBM-Core.lua:1532
 IconNumToTexture = <function> defined @DBM-Core/DBM-Core.lua:6821
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core/DBM-Core.lua:2426
 AddDefeatSound = <function> defined @DBM-Core/modules/Sounds.lua:117
 SortByMeleeRoster = <function> defined @DBM-Core/DBM-Core.lua:7680
 HudMap = <table> {
 }
 GetBossUnitId = <function> defined @DBM-Core/DBM-Core.lua:2696
 lastAntiSpamFLASH = 4657.984000
 AddDefaultOptions = <function> defined @DBM-Core/DBM-Core.lua:2812
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core/DBM-Core.lua:3782
 InfoFrame = <table> {
 }
 SendCombatInfo = <function> defined @DBM-Core/DBM-Core.lua:6387
 FilterRaidBossEmote = <function> defined @DBM-Core/DBM-Core.lua:1367
 RequestTimers = <function> defined @DBM-Core/DBM-Core.lua:6262
 CINEMATIC_START = <function> defined @DBM-Core/DBM-Core.lua:6875
 VoiceVersions = <table> {
 }
 Vo
